# Generated by Django 5.0.7 on 2024-07-21 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Название')),
                ('name_ascii', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Название в кодировке ascii')),
                ('latitude', models.FloatField(max_length=32, verbose_name='Широта')),
                ('longitude', models.FloatField(max_length=32, verbose_name='Долгота')),
                ('country', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Страна')),
                ('iso2', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Сокращенное название ISO-2')),
                ('iso3', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Сокращенное название ISO-3')),
                ('region', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Регион/область')),
                ('admin_name', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Имя администратора')),
                ('population', models.PositiveIntegerField(verbose_name='Население')),
                ('id_number', models.PositiveIntegerField(verbose_name='Идентификатор')),
            ],
        ),
    ]
