# Generated by Django 5.0.7 on 2024-07-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='admin_name',
        ),
        migrations.RemoveField(
            model_name='city',
            name='id_number',
        ),
    ]
